/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";

import type { MathUtils } from "../MathUtils";

export class MathUtils__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MathUtils> {
    return super.deploy(overrides || {}) as Promise<MathUtils>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MathUtils {
    return super.attach(address) as MathUtils;
  }
  connect(signer: Signer): MathUtils__factory {
    return super.connect(signer) as MathUtils__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MathUtils {
    return new Contract(address, _abi, signerOrProvider) as MathUtils;
  }
}

const _abi = [
  {
    inputs: [],
    name: "PERC_DIVISOR",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60c4610052600b82828239805160001a607314610045577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe730000000000000000000000000000000000000000301460806040526004361060335760003560e01c8063cce2a078146038575b600080fd5b603e6052565b604051604991906075565b60405180910390f35b670de0b6b3a764000081565b6000819050919050565b606f81605e565b82525050565b6000602082019050608860008301846068565b9291505056fea2646970667358221220009321d10db2da19c9c96fca4a910d938510c16d0fd7d0cbe05d2725a6ae80a264736f6c63430008090033";
